[tools]
rojo = { github = "rojo-rbx/rojo", version = "=7.3.0" }
selene = { github = "Kampfkarren/selene", version = "=0.25.0" }
stylua = { github = "JohnnyMorganz/styLua", version = "=0.18.1" }
darklua = { github = "seaofvoices/darklua", version = "=0.10.2" }
luau-lsp = { github = "JohnnyMorganz/luau-lsp", version = "=1.24.0" }
